base_url = "https://qimatr.github.io/"
title = "ุงูููููุทูุฑู"

default_language = "ar"
compile_sass = true
generate_feeds = true
feed_filenames = ["rss.xml"]
author = "ูุญูุฏ"
# ุฅุฐุง ุชู ุงุณุชุฎุฏุงูู ููุงูุจุ ูุฑุฌู ุฅูุบุงุก ุชุนููู ูุฐุง ุงูุฎูุงุฑ
# theme = "Re137"

# ูุชูุนูู ุตูุญุฉ ุงูุชุตูููุงุช
 taxonomies = [{ name = "categories" }]

[slugify]
paths = "safe"
taxonomies = "safe"
anchors = "safe"

[extra]
year_template = "year.html"

# ุงูุตูุฑุฉ ุงููุนุฑูุถุฉ ุนูุฏ ูุดุงุฑูุฉ ุงููููุน
# ogimage = " "

# ุฅุนุฏุงุฏุงุช SEO
# seo = true
# google_search_console = " "

# ุฅุธูุงุฑ ุฃุฒุฑุงุฑ ุงูููุฒ ููIndiewebring
indiewebring = false

# ูููุตุงุฏูุฉ ูู Mastodon
# mastodon = "https://o3o.ca/@tinikov"

# ููุทูุจ ุงุณู ุงููุณุชุฎุฏู ููุท
# github = "tinikov"

# ุฅุธูุงุฑ ุชุงุฑูุฎ ุงูุชุฃุณูุณ ูู ุงูุชุฐููู
establishdate = "2024"

# ุฑุฎุตุฉ ุงููุดุงุน ุงูุฅุจุฏุงุนู BY-NC 4.0
license = false

# ุฅุธูุงุฑ "Zola &laquo; re137" ูู ุงูุชุฐููู
show_zola_theme = true
build_search_index = true

# ููููู ุฅุถุงูุฉ ุนูุงุตุฑู ุงูุฎุงุตุฉ ูู ูุงุฆูุฉ ุงูุชููู ุจุงููููุน
re137_menu_links = [
    { url = "$BASE_URL", name = "ุงูุตูุญุฉ ุงูุฑุฆูุณูุฉ ๐" },
    { url = "$BASE_URL/blog", name = "ุงููููููุงุดูุฉู โ๏ธ" },  # ููู ุงูุญุจุฑ ุงููุฏูู
    { url = "$BASE_URL/categories", name = "ุงูุชุตูููุงุช ๐๏ธ" },  # ูุฌูุฏ ุงูุชุตูููุงุช
     { url = "$BASE_URL/rss.xml", name = "ุงูููุฌุฒ ๐ก" },
]

